### PR TITLE
Fix bug in content loading for story queries

### PR DESCRIPTION
**Pull request by e-wai**
## Notion ticket link

[Fully load content on storyByID](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=d2730d8328e948b4be291b19c2aaf126)

## Implementation description
* I don't know why this fixes anything I'm sorry

## Steps to test
1. Set up your DBs, make sure that you have at least one story
2. Test query:
```
{
  storyById(id: 2) {
    id
    title
    contents {
      id
      storyId
      lineIndex
      content
    }
  }
  stories {
    id
    contents {
      id
      storyId
      lineIndex
      content
    }
  }
}
```
3. Make sure `contents` field is not null on either! Either empty array `"contents": []` or something like
```
"contents": [
  {
    "id": 1,
    "storyId": "1",
    "lineIndex": 0,
    "content": "Line 1"
  },
  {
    "id": 2,
    "storyId": "1",
    "lineIndex": 1,
    "content": "Line 2"
  }
]
```

## What should reviewers focus on?
* _why does this work_ 🐋 🐳 🐋 
* About lazy-loading, I chose default behaviour there are sufficient cases where I see us querying without wanting all the content details. Reference here -> https://docs-sqlalchemy.readthedocs.io/ko/latest/orm/loading_relationships.html

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] For backend changes, I have run the appropriate linters:  `docker exec -it <backend-container-id> /bin/bash -c "black . && isort --profile black ."`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by gaoxk — CHANGES_REQUESTED** [review]
Aha! Interesting, [here's ](https://github.com/uwblueprint/planet-read/blob/main/backend/python/app/models/story.py#L21) why `to_dict` was having trouble. We need to pass it` include_relationships=True` to get the contents. 
We should still err on the side of using `to_dict` to make sure we're never returning more information than necessary. Returning the model object directly runs that risk.

**Comment by e-wai** [comment]
Hmm it's still not working when I toggle `include_relationships` to `True`

**Comment by gaoxk** [comment]
🤔 are you sure? It works locally for me
changed lines are
```
return [result.to_dict(include_relationships=True) for result in Story.query.all()]
...
return story.to_dict(include_relationships=True)
```

**Comment by e-wai** [comment]
Ah, I was making changes to StoryContent instead of Story. Should be fixed!

**Review by gaoxk — APPROVED** [review]
:shipit:

**Pull request merged**
