### PR TITLE
Fix: clear + refresh window when tokens are expired

### PR DESCRIPTION
**Pull request by gaoxk**
## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description

aight so theres two potential causes to issues people (eg @lynn-kim @Puepis @jennchenn ) were seeing yesterday night
1. refreshing tokens too often makes firebase upset
2. auth tokens might get cleared from local storage if a token is expired, but unless a page is refreshed or an error is thrown, the gql request will still go through and come back with errors

I was able to explicitly encounter 2, but not 1. heres what I did to try to fix things:
- tokens are never refreshed along side a request. ie, if you log in at 3:30, you'll be booted by 4:30 no matter what
- reload the window + throw an error if an expired token is encountered during a gql request

## Steps to test

1. checkout main (NOT THIS BRANCH)
2. login in non-incognito. keep the tab open
  i. you can continue dev work in a different browser (eg firefox) or in incognito

new for this ticket
3. click around and try to get stuck. I tested getting the browse stories tab stuck in loading for ever, and seeing firebase issues over the network
4. checkout this branch
5. reload/refresh your page
  i. if you accidentally deleted your tab, no problemo. when you open localhost:3000 you should still be brought to the login page
6. observe redirect to login page and cleared cookies

retesting from previous [clear cookie ticket](https://github.com/uwblueprint/planet-read/pull/295)
3. come back to this ticket in an hour. observe that you're stuck as outlined on the ticket
4. checkout this branch
5. reload/refresh your page
  i. if you accidentally deleted your tab, no problemo. when you open localhost:3000 you should still be brought to the login page
6. observe redirect to login page and cleared cookies

## What should reviewers focus on?

- does it work
- lmk any other observations deets when you encounter problems. I find the errors coming back from firebase to be somewhat misleading at times (eg, expired token errors when theres actually no token getting passed at all)

## Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] For backend changes, I have run the appropriate linters: `docker exec -it planet-read_py-backend_1 /bin/bash -c "black . && isort --profile black ."` and I have generated new migrations: `flask db migrate -m "<your message>"`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by gaoxk** [comment]
opened as ready pr rather than draft to generate firebase deployment for testing

**Comment by gaoxk** [comment]
ready for review now

**Review by Puepis — COMMENTED** [review]
when I follow the steps, I don't get logged out after switching branches and reloading the page. instead I'm stuck on the same page and I get an authorization error: ```[GraphQL error]: Message: You are not authorized to make this request., Location: [object Object], Path: storyTranslations```

I also tried checking whether the access token was expired in `injectAccessToken` but it isn't expired

image

i'm gonna try investigating the cause

**Comment by lynn-kim** [comment]
Same as Philips, when I checked out to this branch after getting stuck the backend logs indicate that the token was cleared but didn't get logged out on the frontend. 

Screen Shot 2022-01-04 at 8 40 15 PM

Screen Shot 2022-01-04 at 8 40 52 PM

**Comment by gaoxk** [comment]
AIGHT OK SO the real issue is 
- logging out a user revokes all their tokens 
- so active tokens elsewhere (eg in a different browser, on a different computer) become expired and dont work 
- short term fix is to just stop revoking tokens when logging out a user. IMO security risk is minimal since token expires in an hour anyways. tokens could still be revoked for other reasons (eg user disabled due to security incident) so we should find some way of detecting a revoked token in the gql client to clear the cache

to test new fixes
- login as a user
- login as same user in different browser/incognito
- logout immeditately 
- observe that original tab can still correctly complete requests

**Review by Puepis — APPROVED** [review]
LGTM!!

**Comment by gaoxk** [comment]
TFTR!!!!

**Pull request merged**
