### PR TITLE
Link to user instead of translation 

### PR DESCRIPTION
**Pull request by lynn-kim**
## Notion ticket link

[MyTest table user link uses story_translation_id instead of user_id](https://www.notion.so/uwblueprintexecs/MyTest-table-user-link-uses-story_translation_id-instead-of-user_id-ad2fa10b2c4b46d4b3b0bc52d7ff0f2b)

## Implementation description

- Use translatorId instead of id

## Steps to test

1. Login as admin and go to http://localhost:3000/ 
2. Check that clicking on the name brings you to the correct profile

## What should reviewers focus on?

- Does it work

## Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] For backend changes, I have run the appropriate linters: `docker exec -it planet-read_py-backend_1 /bin/bash -c "black . && isort --profile black ."` and I have generated new migrations: `flask db migrate -m "<your message>"`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by Puepis — APPROVED** [review]
LGTM! 🚢

**Comment by gaoxk** [comment]
uhhh the network call comes back with tests but the table is empty. can you double check youre not seeing this on your side?
image

**Comment by lynn-kim** [comment]
@gaoxk I think the stage needs to be review for it to show up in the table. Do we wanna change it so that all tests show up, regardless of stage?

**Comment by gaoxk** [comment]
@lynn-kim AH thats right, my bad. dont mind my poor memory. LGTM, feel free to merge!

**Pull request merged**
